### ISSUE TITLE
No valid GraphQL endpoint: __RELAY_API_ENDPOINT__

### ISSUE THREAD

**Issue by optimistiks** [graphcool-examples/react-relay-instagram-example#26]
React + Relay example does not work out of the box in Ubuntu 14, node 6, npm 3.

Steps to reproduce: 
- Download the example using the blue "Download example" button
- Unzip, run npm install, run npm start

Expected: Application started
Actual: Error
```
ERROR in ./src/index.js
Module build failed: Error: No valid GraphQL endpoint: __RELAY_API_ENDPOINT__
    at parse (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/graphql-config-parser/src/index.js:34:19)
    at Object.<anonymous> (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-plugin-react-relay/lib/index.js:53:45)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:178:20
    at Array.map (native)
    at Function.normalisePlugins (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/optimistiks/projects/react-relay-instagram-example-master/node_modules/babel-core/lib/transformation/file/index.js:135:24)
 @ multi main

```

**Comment by marktani** [comment]
Thanks for the detailed report @optimistiks :slightly_smiling_face:
